# simple docker-compose.yml file for nats redis
version: '3'
services:
  nats:
    image: nats:2.6.6-alpine3.14
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - ./volumes/nats:/data
    restart: always
  redis:
    image: redis:6.2.6-alpine3.15
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
    restart: always
